// Generated by LiveScript 1.3.1
(function(){
  var express, path, getsecret, bing_api_key, Bing, app, get_image_url;
  express = require('express');
  path = require('path');
  getsecret = require('getsecret');
  bing_api_key = getsecret('bing_api_key');
  Bing = require('node-bing-api')({
    accKey: bing_api_key
  });
  app = express();
  app.set('port', process.env.PORT || 8080);
  app.use(express['static'](path.join(__dirname, '')));
  get_image_url = function(query, callback){
    return Bing.images(query, {}, function(error, res2, body){
      return callback(body.d.results[0].MediaUrl);
    });
  };
  app.get('/image', function(req, res){
    return get_image_url(req.query.name, function(imgurl){
      return res.send(imgurl);
    });
  });
  app.listen(app.get('port'), '0.0.0.0');
}).call(this);
